kafka:
  bootstrap_servers: "kafka-broker-1:9092"
  num_partitions: 3
  replication_factor: 1
  topic:
    raw_messages: "raw_messages"
    embeddings: "embeddings"
  event:
    text_column: "text"
    vector_column: "embedding"
  consumers:
    preprocessor_group: "preprocessor_group"
    clusterer_group: "clusterer_group"

dataset:
  file_path: "test/data/twitter_dataset_1000.csv"
  chunk_size: 1000
  text_column: "text"

ml:
  embedding_model: "all-MiniLM-L6-v2"
  pca_components_num: 50

denstream:
  epsilon: 0.3
  mu: 2
  decaying_factor: 0.01

postgres:
  tables:
    params: "model_parameters"
    results: "clustering_results"
